name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  setup-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Setup GCP Auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Verify Secret Access (**REMOVE BEFORE COMMIT**!)
        run: |
              echo "Secret value: ${{ secrets.GCP_SA_KEY }}"

      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2.2.0 # Replace with the latest version
        with:
          service: my-service # Replace with your service name
          region: asia-northeast1 # Replace with your desired region
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/triage-app:${{ github.sha }} # Reference your image location
          # Additional configuration options for Cloud Run deployment (refer to action documentation)

      

      # The rest of your deployment steps follow...
