name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  setup-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Setup GCP Auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Build and Push Docker image
        run: |
              gcloud auth configure-docker
              docker buildx build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/triage-app:${{ github.sha }}
              

      # The rest of your deployment steps follow...
